// Redux Actions
export const GET_INGREDIENTS = 'GET_INGREDIENTS'
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS'
export const GET_INGREDIENTS_FAILURE = 'GET_INGREDIENTS_FAILURE'

export const RECIPE_SEARCH = 'RECIPE_SEARCH'
export const RECIPE_SEARCH_SUCCESS = 'RECIPE_SEARCH_SUCCESS'
export const RECIPE_SEARCH_NO_RESULTS = 'RECIPE_SEARCH_NO_RESULTS'
export const RECIPE_SEARCH_FAILURE = 'RECIPE_SEARCH_FAILURE'

export const RECIPE_ID_SEARCH = 'RECIPE_ID_SEARCH'
export const RECIPE_ID_SEARCH_SUCCESS = 'RECIPE_ID_SEARCH_SUCCESS'
export const RECIPE_ID_SEARCH_FAILURE = 'RECIPE_ID_SEARCH_FAILURE'

export const emptyfunction = () => {}